### ISSUE TITLE
out of disk space during gcc build

### ISSUE THREAD

**Issue by N7DR** [slyfox1186/script-repo#12]
It looks, to the extent that I understand the gcc-build.sh script, like it is supposed to figure out whether there is sufficient disk space for it to execute.

I think that this is supposed to happen with the line:
  check_disk_space 5000

It seems that perhaps that number is too small. I just tried to run the script in a VM with about 6GB free, building gcc 14.2, and after an hour or so it halted with an error message stating that it had run out of disk space.

**Comment by N7DR** [comment]
Hmmm... I re-tried the build, with 14GB free, and it again ran out of space. So perhaps I am wrong and the script does not attempt to warn if there is insufficient disk space?

I am currently trying again with 24GB free.

**Comment by N7DR** [comment]
With 24GB free, the script did not run out of space, but then it hit issue #13.

**Comment by slyfox1186** [comment]
I will close this as well. Thanks.
