### ISSUE TITLE
build-gcc does not check and warn if libtool is missing

### ISSUE THREAD

**Issue by N7DR** [slyfox1186/script-repo#13]
Trying to build GCC version 14, the script eventually tries to execute:

sudo libtool --finish /usr/local/programs/gcc-14.2.0/libexec/gcc/x86_64-linux-gnu/14

This produced:

sudo: libtool: command not found

[ERROR 07:56:34 AM] Failed to execute sudo libtool --finish /usr/local/programs/gcc-14.2.0/libexec/gcc/x86_64-linux-gnu/14

The script should check for the existence of libtool early during its execution, and install it if it is not present.

**Comment by N7DR** [comment]
Oh, this is weird:

n7dr@debian-bookworm-12-64:~$ sudo apt install libtool
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libtool is already the newest version (2.4.7-7~deb12u1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
n7dr@debian-bookworm-12-64:~$ 

So I don't know why the script is failing to execute libtool.

My best guess is that whatever $PATH is used under "sudo", it doesn't include the directory in which libtool is located:

n7dr@debian-bookworm-12-64:~$ whereis libtool
libtool: /usr/share/libtool
n7dr@debian-bookworm-12-64:~$ 

n7dr@debian-bookworm-12-64:~$ sudo echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
n7dr@debian-bookworm-12-64:~$ 

Yep, that looks like it's the problem. This is on a brand-new debian bookworm VM created yesterday solely for the purpose of testing build-gcc.sh.

**Comment by N7DR** [comment]
Hmmm... I'm completely confused. /usr/share/libtool is actually a directory. I can't find where the tool is actually installed. I see that the script lists libtool as a dependency, which is probably why it's installed, but for some reason the actual call to  "sudo libtool --finish /usr/local/programs/gcc-14.2.0/libexec/gcc/x86_64-linux-gnu/14" fails, as noted above.

So at this point I'm stuck, and cannot correctly build and install GCC 14 :-(

**Comment by N7DR** [comment]
I don't know how to push a fix, but it's an easy change:

add libtool-bin to pkgs in the install_deps() function.

**Comment by slyfox1186** [comment]
ill add this to the list of packages

libtool-bin

thanks for the help!
