### ISSUE TITLE
building zstd - version 1.5.5 failed

### ISSUE THREAD

**Issue by yibudak** [slyfox1186/script-repo#2]
I got this error when executing `bash <(curl -fsSL https://gcc.optimizethis.net)`

Error:

```
building zstd - version 1.5.5
====================================
Downloading "https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-1.5.5.tar.gz" saving as "zstd-1.5.5.tar.gz"
Download Completed
File extracted: zstd-1.5.5.tar.gz

$ meson setup build --prefix=/home/yibudak/gcc-build-script/workspace --buildtype=release --default-library=static --strip
$ ninja -j12 -C build                                                                               
Cannot autolaunch D-Bus without X11 $DISPLAY


Failed to execute: ninja -j12 -C build

Please create a support ticket so I can work on a fix.

https://github.com/slyfox1186/script-repo/issues
```

System information:
OS: Ubuntu 22.04.2 LTS x86_64
Kernel: 6.4.6-060406-generic 
Shell: zsh 5.8

**Comment by slyfox1186** [comment]
Try installing dbus-x11 with APT. 

Then, if that doesn't work, delete, the entire zstd code and skip it. 

It's nice to have the latest installed but isn't necessarily essential to the build.

**Comment by slyfox1186** [comment]
Any luck?

**Comment by slyfox1186** [comment]
I added some default variables back into the script environment. This might have been the issue. Give it a try and if needed re-open this ticket if not solved.

tmp_display="$DISPLAY"
tmp_dbus="$DBUS_SESSION_BUS_ADDRESS"
