### ISSUE TITLE
Build-gcc error Ubuntu jammy

### ISSUE THREAD

**Issue by DarkenLX** [slyfox1186/script-repo#3]
` ------------------------
|                        |
| GCC Build Script: v4.1 |
|                        |
 ------------------------
Installing required python packages
================================================

Collecting types-gdb
  Downloading types_gdb-12.1.4.5-py3-none-any.whl (10 kB)
Collecting os.path2
  Downloading os.path2-0.0.4.tar.gz (6.5 kB)
  Preparing metadata (setup.py) ... done
Collecting mbs-sys
  Downloading mbs_sys-0.4.tar.gz (1.8 kB)
  Preparing metadata (setup.py) ... done
Collecting tempfile2
  Downloading tempfile2-0.1.2.tar.gz (3.1 kB)
  Preparing metadata (setup.py) ... done
Collecting PrettyGcov
  Downloading PrettyGcov-1.2.0-py3-none-any.whl (13 kB)
Collecting json2json
  Downloading json2json-0.1.0-py3-none-any.whl (7.7 kB)
Collecting pytest
  Downloading pytest-7.4.0-py3-none-any.whl (323 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 323.6/323.6 KB 372.9 kB/s eta 0:00:00
Collecting csv23
  Downloading csv23-0.3.4-py2.py3-none-any.whl (18 kB)
Collecting time-tools
  Downloading time_tools-1.0.0-py2.py3-none-any.whl (5.5 kB)
Collecting argparse3
  Downloading argparse3-0.0.0-py3-none-any.whl (2.1 kB)
Collecting pathlib
  Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Collecting shutil-extra
  Downloading shutil_extra-0.0.6.tar.gz (3.5 kB)
  Preparing metadata (setup.py) ... done
Collecting latex
  Downloading latex-0.7.0.tar.gz (6.5 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pygments in /usr/lib/python3/dist-packages (2.11.2)
Collecting pluggy<2.0,>=0.12
  Downloading pluggy-1.3.0-py3-none-any.whl (18 kB)
Collecting exceptiongroup>=1.0.0rc8
  Downloading exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pytest) (21.3)
Collecting tomli>=1.0.0
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting iniconfig
  Downloading iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
Collecting data
  Downloading data-0.4.tar.gz (7.0 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from latex) (0.18.2)
Collecting shutilwhich
  Downloading shutilwhich-1.1.0.tar.gz (2.3 kB)
  Preparing metadata (setup.py) ... done
Collecting tempdir
  Downloading tempdir-0.7.1.tar.gz (5.9 kB)
  Preparing metadata (setup.py) ... done
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting funcsigs
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from data->latex) (1.16.0)
Building wheels for collected packages: os.path2, mbs-sys, tempfile2, shutil-extra, latex, data, shutilwhich, tempdir
  Building wheel for os.path2 (setup.py) ... done
  Created wheel for os.path2: filename=os.path2-0.0.4-py3-none-any.whl size=7563 sha256=4d56dbac77197aee8106499822be6b0fcc2b76337035738afc5bb4996c93b3ed
  Stored in directory: /home/louis/.cache/pip/wheels/2b/90/50/58b95bafe84eff119dddce98cf08a65a3d8773248ff2cbbc51
  Building wheel for mbs-sys (setup.py) ... done
  Created wheel for mbs-sys: filename=mbs_sys-0.4-py3-none-any.whl size=1901 sha256=7e6ee6c28c89d946e5229f85e99dbc8eab366a5bbe6fc85007fee6c9345fd1e7
  Stored in directory: /home/louis/.cache/pip/wheels/ef/ae/3d/54b6396d8b53a52521eef8af2fd825144476d17d684cc769df
  Building wheel for tempfile2 (setup.py) ... done
  Created wheel for tempfile2: filename=tempfile2-0.1.2-py3-none-any.whl size=2966 sha256=2045599be5e2d29cc1e3034414ae5026339512ead6eee21435fe7dcb77668077
  Stored in directory: /home/louis/.cache/pip/wheels/9e/30/93/1c67a4daeb7aafd329312ebf20870ae97644bfc38f1cdce0f1
  Building wheel for shutil-extra (setup.py) ... done
  Created wheel for shutil-extra: filename=shutil_extra-0.0.6-py3-none-any.whl size=3944 sha256=e3d9496bbe1e4b622d5d26a572603fb607053b6ec1707389a38feee2847558b0
  Stored in directory: /home/louis/.cache/pip/wheels/af/ad/63/0fe5127e96840357d8b88102965adcbc91e1ef24690555f90b
  Building wheel for latex (setup.py) ... done
  Created wheel for latex: filename=latex-0.7.0-py3-none-any.whl size=7604 sha256=ca1274ffaf7c65398b325460c8cff716a51b4e3a78511886c220e1c8232a541e
  Stored in directory: /home/louis/.cache/pip/wheels/7e/02/25/c00dfc203e8ba53dfc2e4e97d40e537263d6e03606681f3872
  Building wheel for data (setup.py) ... done
  Created wheel for data: filename=data-0.4-py3-none-any.whl size=7244 sha256=58bf9ab8d54e0d206f5d05680d40d133a4cdce2658e78eb23146d2267e5b238a
  Stored in directory: /home/louis/.cache/pip/wheels/d0/e8/fa/e253c256048ea58d99a8abb5e751abb6a838af6f12887b5418
  Building wheel for shutilwhich (setup.py) ... done
  Created wheel for shutilwhich: filename=shutilwhich-1.1.0-py3-none-any.whl size=2781 sha256=1188eaf95b08761541f7c39511a1857c8961496f7c0fc4222137db67d475e695
  Stored in directory: /home/louis/.cache/pip/wheels/75/1f/1c/0ecab7ceabad0b8e018891505911e82a6f358a0291e7681bae
  Building wheel for tempdir (setup.py) ... done
  Created wheel for tempdir: filename=tempdir-0.7.1-py3-none-any.whl size=2214 sha256=2e9e04f5acd82409691dd776cf44e016d15a0894a7aef2c9fef76c25e089a106
  Stored in directory: /home/louis/.cache/pip/wheels/c6/9a/9d/44903aa5aac6c6bc5f0c331ed86214bbedce17e8556d002f1a
Successfully built os.path2 mbs-sys tempfile2 shutil-extra latex data shutilwhich tempdir
Installing collected packages: types-gdb, tempfile2, tempdir, shutilwhich, shutil-extra, PrettyGcov, pathlib, os.path2, mbs-sys, funcsigs, argparse3, tomli, time-tools, pluggy, json2json, iniconfig, exceptiongroup, decorator, csv23, pytest, data, latex
Successfully installed PrettyGcov-1.2.0 argparse3-0.0.0 csv23-0.3.4 data-0.4 decorator-5.1.1 exceptiongroup-1.1.3 funcsigs-1.0.2 iniconfig-2.0.0 json2json-0.1.0 latex-0.7.0 mbs-sys-0.4 os.path2-0.0.4 pathlib-1.0.1 pluggy-1.3.0 pytest-7.4.0 shutil-extra-0.0.6 shutilwhich-1.1.0 tempdir-0.7.1 tempfile2-0.1.2 time-tools-1.0.0 tomli-2.0.1 types-gdb-12.1.4.5

building m4 - version latest

m4 version latest already built. Remove /home/louis/gcctmp/gcc-build-script/packages/m4.done lockfile to rebuild it.

building automake - version 1.16.5

automake version 1.16.5 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/automake.done lockfile to rebuild it.

building libtool - version 2.4.7

libtool version 2.4.7 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/libtool.done lockfile to rebuild it.

building autoconf-v271 - version 2.71

autoconf-v271 version 2.71 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/autoconf-v271.done lockfile to rebuild it.

building bison - version git

bison version git already built. Remove /home/louis/gcctmp/gcc-build-script/packages/bison.done lockfile to rebuild it.

building gettext - version 0.21.1

gettext version 0.21.1 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/gettext.done lockfile to rebuild it.

building libiconv - version 1.17

libiconv version 1.17 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/libiconv.done lockfile to rebuild it.

building diffutils - version 3.9

diffutils version 3.9 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/diffutils.done lockfile to rebuild it.

building attr - version 2.5.1

attr version 2.5.1 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/attr.done lockfile to rebuild it.

building patch - version 2.7.6

patch version 2.7.6 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/patch.done lockfile to rebuild it.

building gmp - version 6.2.1

gmp version 6.2.1 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/gmp.done lockfile to rebuild it.

building isl - version 0.24

isl version 0.24 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/isl.done lockfile to rebuild it.

building gperftools - version 2.12

gperftools version 2.12 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/gperftools.done lockfile to rebuild it.

building zstd - version 1.5.5

The file "zstd-1.5.5.tar.gz" is already downloaded.
File extracted: zstd-1.5.5.tar.gz

$ meson setup build --prefix=/home/louis/gcctmp/gcc-build-script/workspace --buildtype=release --default-library=static --strip
$ ninja -j8 -C build
Cannot autolaunch D-Bus without X11 $DISPLAY

Failed to execute: ninja -j8 -C build

Please create a support ticket so I can work on a fix.

https://github.com/slyfox1186/script-repo/issues
`
not sure whats going on i ran the script twice as it gave this same error the first time so i dont know what the issue currently is..

**Comment by slyfox1186** [comment]
I have seen this issue before. I was hoping that adding the native DISPLAY variable back into the script would solve it for everyone but maybe not.

Try running this script and the try again.

https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/FFmpeg/ffmpeg-fix-dbus.sh

**Comment by DarkenLX** [comment]
> I have seen this issue before. I was hoping that adding the native DISPLAY and DBUS_SESSION_BUS_ADDRESS variables back into the script would solve it for everyone...
> 
> Try running this script first and then try again.
> 
> https://github.com/slyfox1186/script-repo/blob/main/Bash/Installer%20Scripts/FFmpeg/ffmpeg-fix-dbus.sh

ran that and tried again. still getting same error.

**Comment by slyfox1186** [comment]
1. Download the script to a file.
2. Remove all lines from 77-96
3. run script `bash script-name.sh`

If that doesn't work then I will have to rethink what is happening. It appears an essential variable is missing and by removing the above lines as mentioned it should eliminate all of the default variables.

I hope you have better luck this time. My build works fine on Debian 12...

**Comment by DarkenLX** [comment]
> 1. Download the script to a file.
> 2. Remove all lines from 77-96
> 3. run script `bash script-name.sh`
> 
> If that doesn't work then I will have to rethink what is happening. It appears an essential variable is missing and by removing the above lines as mentioned it should eliminate all of the default variables from being removed.
> 
> I hope you have better luck this time. My build works fine on Debian 12...

done that still getting the same error

building m4 - version latest
====================================
m4 version latest already built. Remove /home/louis/gcctmp/gcc-build-script/packages/m4.done lockfile to rebuild it.

building automake - version 1.16.5
====================================
automake version 1.16.5 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/automake.done lockfile to rebuild it.

building libtool - version 2.4.7
====================================
libtool version 2.4.7 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/libtool.done lockfile to rebuild it.

building autoconf-v271 - version 2.71
====================================
autoconf-v271 version 2.71 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/autoconf-v271.done lockfile to rebuild it.

building bison - version git
====================================
bison version git already built. Remove /home/louis/gcctmp/gcc-build-script/packages/bison.done lockfile to rebuild it.

building gettext - version 0.21.1
====================================
gettext version 0.21.1 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/gettext.done lockfile to rebuild it.

building libiconv - version 1.17
====================================
libiconv version 1.17 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/libiconv.done lockfile to rebuild it.

building diffutils - version 3.9
====================================
diffutils version 3.9 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/diffutils.done lockfile to rebuild it.

building attr - version 2.5.1
====================================
attr version 2.5.1 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/attr.done lockfile to rebuild it.

building patch - version 2.7.6
====================================
patch version 2.7.6 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/patch.done lockfile to rebuild it.

building gmp - version 6.2.1
====================================
gmp version 6.2.1 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/gmp.done lockfile to rebuild it.

building isl - version 0.24
====================================
isl version 0.24 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/isl.done lockfile to rebuild it.

building gperftools - version 2.12
====================================
gperftools version 2.12 already built. Remove /home/louis/gcctmp/gcc-build-script/packages/gperftools.done lockfile to rebuild it.

building zstd - version 1.5.5
====================================
The file "zstd-1.5.5.tar.gz" is already downloaded.
File extracted: zstd-1.5.5.tar.gz

$ meson setup build --prefix=/home/louis/gcctmp/gcc-build-script/workspace --buildtype=release --default-library=static --strip
$ ninja -j8 -C build


Failed to execute: ninja -j8 -C build

Please create a support ticket so I can work on a fix.

https://github.com/slyfox1186/script-repo/issues

would any of this be because im using the mainline kernels? i cant use any kernel older than 6.x as my pc has hardware only usable in 6.x kernels.. it doesn't seem kernel related judging by the error.

**Comment by slyfox1186** [comment]
I changed zstd from meson to cmake as I was having trouble building using Ubuntu Jammy as well. Once I did that everything worked fine see if it works for you.

**Comment by DarkenLX** [comment]
> I changed zstd from meson to cmake as I was having trouble building using Ubuntu Jammy as well. Once I did that everything worked fine see if it works for you.

so.. just change anything meson in the script to cmake?

**Comment by slyfox1186** [comment]
No, I changed it in the main script, so just update the script.
Regards,

Jeff Hollis
Pooler, GA 31322
Cell: 678-956-3100

**Comment by slyfox1186** [comment]
If this is still a problem just re-open the ticket.
